version: '3.8'
services:
  app:
    container_name: EA-BackEnd
    restart: always
    build: .
    ports:
      - '8001:4000'
    depends_on:
      - mongo
  mongo:
    container_name: EA-BackEnd-Mongo
    image: mongo
    expose:
      - '27017'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - backendDB:/data/db
  
volumes:
  backendDB:
